# Generated by Django 5.0.7 on 2025-02-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
