# Generated by Django 5.0.7 on 2025-03-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='late_fine',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
